book:
  service:
    title: Cloud Native Java
    price: 50
    author: Jose Long
management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health